# Generated by Django 3.2.6 on 2021-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul', models.CharField(default='', max_length=64)),
                ('Rezyser', models.CharField(default='', max_length=64)),
                ('Czas_trwania', models.IntegerField(default=0)),
                ('Data_wydania', models.DateField()),
                ('Ocena', models.CharField(choices=[('A', 'Bardzo dobry'), ('B', 'Dobry'), ('C', 'Sredni'), ('D', 'Slaby'), ('E', 'Bardzo slaby'), ('F', 'Beznadziejny')], default='Dobry', max_length=24)),
            ],
        ),
    ]
