# Generated by Django 3.2.6 on 2021-08-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zadanieApi', '0002_film_inspirujacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Inspirujacy',
            new_name='Oparty_na_ksiazce',
        ),
    ]
