# Generated by Django 3.2.6 on 2021-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanieApi', '0003_rename_inspirujacy_film_oparty_na_ksiazce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Oparty_na_ksiazce',
            field=models.BooleanField(default=True),
        ),
    ]
